### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ghost** [vadimcn/cargo-pgo#2]
Could you please add a license to your code? I would prefer MIT and/or Apache2, but that is up to you.

**Comment by vadimcn** [comment]
Why?   I think this stuff has been superseded by PGO support in rustc itself.

**Comment by ghost** [comment]
I still see a lot of potential in a pgo cargo command, but now that I'm thinking about it, I will propably write a new Cargo plugin for this. I would need to change way to much about how this is used.
